<?php
declare(strict_types=1);

namespace ArrayAccess\WP\Libraries\Core\Util;

use function in_array;
use function is_string;
use function strtolower;
use function trim;

class HighlightJS
{
    public const VERSION = '11.9.0';

    /**
     * @var string
     */
    public const DEFAULT_THEME = 'default';

    /**
     * @var string[]
     */
    public const THEMES = [
        'a11y-dark',
        'a11y-light',
        'agate',
        'an-old-hope',
        'androidstudio',
        'arduino-light',
        'arta',
        'ascetic',
        'atom-one-dark',
        'atom-one-dark-reasonable',
        'atom-one-light',
        'brown-paper',
        'codepen-embed',
        'color-brewer',
        'dark',
        'default',
        'devibeans',
        'docco',
        'far',
        'felipec',
        'foundation',
        'github',
        'github-dark',
        'github-dark-dimmed',
        'gml',
        'googlecode',
        'gradient-dark',
        'gradient-light',
        'grayscale',
        'hybrid',
        'idea',
        'intellij-light',
        'ir-black',
        'isbl-editor-dark',
        'isbl-editor-light',
        'kimbie-dark',
        'kimbie-light',
        'lightfair',
        'lioshi',
        'magula',
        'mono-blue',
        'monokai',
        'monokai-sublime',
        'night-owl',
        'nnfx-dark',
        'nnfx-light',
        'nord',
        'obsidian',
        'panda-syntax-dark',
        'panda-syntax-light',
        'paraiso-dark',
        'paraiso-light',
        'pojoaque',
        'purebasic',
        'qtcreator-dark',
        'qtcreator-light',
        'rainbow',
        'routeros',
        'school-book',
        'shades-of-purple',
        'srcery',
        'stackoverflow-dark',
        'stackoverflow-light',
        'sunburst',
        'tokyo-night-dark',
        'tokyo-night-light',
        'tomorrow-night-blue',
        'tomorrow-night-bright',
        'vs',
        'vs2015',
        'xcode',
        'xt256',
    ];
    public const LANGUAGE = [
        '1c',
        'abnf',
        'accesslog',
        'actionscript',
        'ada',
        'angelscript',
        'apache',
        'applescript',
        'arcade',
        'arduino',
        'armasm',
        'asciidoc',
        'aspectj',
        'autohotkey',
        'autoit',
        'avrasm',
        'awk',
        'axapta',
        'bash',
        'basic',
        'bnf',
        'brainfuck',
        'c',
        'cal',
        'capnproto',
        'ceylon',
        'clean',
        'clojure',
        'clojure-repl',
        'cmake',
        'coffeescript',
        'coq',
        'cos',
        'cpp',
        'crmsh',
        'crystal',
        'csharp',
        'csp',
        'css',
        'd',
        'dart',
        'delphi',
        'diff',
        'django',
        'dns',
        'dockerfile',
        'dos',
        'dsconfig',
        'dts',
        'dust',
        'ebnf',
        'elixir',
        'elm',
        'erb',
        'erlang',
        'erlang-repl',
        'excel',
        'fix',
        'flix',
        'fortran',
        'fsharp',
        'gams',
        'gauss',
        'gcode',
        'gherkin',
        'glsl',
        'gml',
        'go',
        'golo',
        'gradle',
        'graphql',
        'groovy',
        'haml',
        'handlebars',
        'haskell',
        'haxe',
        'hsp',
        'http',
        'hy',
        'inform7',
        'ini',
        'irpf90',
        'isbl',
        'java',
        'javascript',
        'jboss-cli',
        'json',
        'julia',
        'julia-repl',
        'kotlin',
        'lasso',
        'latex',
        'ldif',
        'leaf',
        'less',
        'lisp',
        'livecodeserver',
        'livescript',
        'llvm',
        'lsl',
        'lua',
        'makefile',
        'markdown',
        'mathematica',
        'matlab',
        'maxima',
        'mel',
        'mercury',
        'mipsasm',
        'mizar',
        'mojolicious',
        'monkey',
        'moonscript',
        'n1ql',
        'nestedtext',
        'nginx',
        'nim',
        'nix',
        'node-repl',
        'nsis',
        'objectivec',
        'ocaml',
        'openscad',
        'oxygene',
        'parser3',
        'perl',
        'pf',
        'pgsql',
        'php',
        'php-template',
        'plaintext',
        'pony',
        'powershell',
        'processing',
        'profile',
        'prolog',
        'properties',
        'protobuf',
        'puppet',
        'purebasic',
        'python',
        'python-repl',
        'q',
        'qml',
        'r',
        'reasonml',
        'rib',
        'roboconf',
        'routeros',
        'rsl',
        'ruby',
        'ruleslanguage',
        'rust',
        'sas',
        'scala',
        'scheme',
        'scilab',
        'scss',
        'shell',
        'smali',
        'smalltalk',
        'sml',
        'sqf',
        'sql',
        'stan',
        'stata',
        'step21',
        'stylus',
        'subunit',
        'swift',
        'taggerscript',
        'tap',
        'tcl',
        'thrift',
        'tp',
        'twig',
        'typescript',
        'vala',
        'vbnet',
        'vbscript',
        'vbscript-html',
        'verilog',
        'vhdl',
        'vim',
        'wasm',
        'wren',
        'x86asm',
        'xl',
        'xml',
        'xquery',
        'yaml',
        'zephir',
    ];

    /**
     * @param string|mixed $theme
     * @param $found
     * @return string
     */
    public static function filterTheme(mixed $theme, &$found = null): string
    {
        if (!is_string($theme)) {
            return self::DEFAULT_THEME;
        }
        $theme = strtolower(trim($theme));
        $found = in_array($theme, self::THEMES);
        if (!$found) {
            $theme = self::DEFAULT_THEME;
        }
        return $theme;
    }

    /**
     * @param mixed $mode
     * @param $found
     * @return string|null
     */
    public static function filterLanguage(mixed $mode, &$found = null): ?string
    {
        if (!is_string($mode)) {
            return null;
        }
        $mode = strtolower(trim($mode));
        $found = in_array($mode, self::LANGUAGE);
        if (!$found) {
            $mode = null;
        }
        return $mode;
    }
}
